# Default values for student-management-chart.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  imagePullPolicy: IfNotPresent
frontend:
  image:
    repository: louisdevops/student-management-frontend
    tag: "73"
backend:
  image:
    repository: louisdevops/student-management-backend
    tag: "latest"
mysql:
  image:
    repository: mysql
    tag: "8.0"
